export type Language = "zh" | "en";

export const copy = {
  zh: {
    nav: {
      chat: "对话空间",
      creator: "创建智能体",
      tools: "能力库",
      dashboard: "调用链路",
      settings: "基础设置",
    },
    productSubtitle: "AgentForge｜需求到产品/UI实施报告平台",
    siderHint: "先创建 Agent，再澄清需求并生成产品/UI实施报告。当前版本优先保证本地可用。",
    topDescription: "创建 Agent，输入需求，逐步生成多套产品/UI实施报告并交给下游 AI 编程 Agent。",
    language: "语言",
    zh: "中文",
    en: "English",
    loadedAgents: "已添加的智能体",
    enabledCount: "个启用",
    currentChat: "当前对话",
    chatTargetHint: "消息会发送给所有已启用的 Agent。",
    taskSpaces: "任务对话空间",
    spaceCount: "个空间",
    createWorkspace: "创建对话空间",
    editWorkspace: "编辑对话空间",
    createFirstWorkspace: "创建第一个任务对话空间",
    defaultWorkspaceName: "产品/UI实施报告",
    defaultWorkspaceDescription: "需求澄清、方案评审与产品/UI报告架构师协作生成可交给下游 AI 编程 Agent 的实施规格。",
    workspaceNoDescription: "暂未填写任务说明",
    workspaceAgentCount: "个智能体",
    workspaceAgents: "空间内智能体",
    workspaceMember: "当前空间成员",
    workspaceName: "任务名称",
    workspaceDescription: "任务说明（可选）",
    workspaceEditorDesc: "为这个任务命名，并选择参与本次对话与报告生成的智能体。",
    selectWorkspaceAgents: "选择空间内智能体",
    configureWorkspace: "配置对话空间",
    selectWorkspaceFirst: "请先创建或选择一个对话空间",
    clearChat: "清空对话",
    inputPlaceholder: "输入消息，发送给当前启用的 Agent",
    send: "发送",
    noAgents: "还没有智能体。",
    addAgent: "添加智能体",
    noMessages: "还没有消息。",
    deleteAgent: "删除智能体",
    editAgent: "编辑智能体",
    agentEnabled: "已启用",
    agentDisabled: "已停用",
    joinReply: "参与回复",
    you: "你",
    thinking: "正在生成...",
    needName: "请先填写智能体名称。",
    needPrompt: "请填写角色设定 Prompt。",
    needAgent: "请先添加并启用至少一个智能体。你的消息已保留在对话中。",
    sanitizedKey: "部分 Agent 的 API Key 包含中文或全角字符，本次已忽略这些 Key 并继续发送。",
    savedWithSanitizedKey: "已保存 {name}，但 API Key 包含中文或全角字符，本地已忽略该 Key。",
    agentAdded: "已添加智能体：{name}",
    agentUpdated: "已更新智能体：{name}",
    editingAgent: "正在编辑智能体：{name}",
    editCancelled: "已取消编辑，可以继续创建新的智能体。",
    callFailed: "模型调用失败。",
    noStream: "没有收到流式响应。",
    sendFailed: "发送失败。",
    clearDone: "对话记录已清空。本地 Agent 配置仍然保留。",
    currentAgents: "当前智能体",
    currentAgentsDesc: "这里可以查看、编辑、启用或删除已经创建的智能体。",
    apiUrlLabel: "API URL",
    apiKeyConfigured: "已配置密钥",
    apiKeyMissing: "未配置密钥",
    capabilityNames: "能力：{names}",
    emptyAgentsInCreator: "还没有智能体。先在右侧创建一个。",
    capabilityCount: "个能力",
    createAgent: "创建智能体",
    editAgentTitle: "编辑智能体：{name}",
    createAgentDesc: "填写模型连接信息后，智能体会加入对话空间。",
    editingHint: "当前正在修改已有智能体，保存后会覆盖原配置。",
    cancelEdit: "取消编辑",
    agentName: "智能体名称",
    agentNamePlaceholder: "例如：需求澄清师",
    rolePrompt: "角色设定 Prompt",
    promptPlaceholder: "描述这个智能体的职责、语气和输出要求。",
    modelSource: "模型来源",
    modelName: "模型名称",
    apiUrlPlaceholder: "https://api.example.com/v1 或 http://localhost:11434",
    apiKeyLabel: "API Key / API 密钥",
    apiKeyPlaceholder: "请输入 API Key",
    ollamaKeyPlaceholder: "Ollama 本地模型可留空",
    apiKeyKeepHint: "圆点表示密钥已加密保存；不输入新值会保留现有密钥。当前掩码：{key}",
    apiKeyNewHint: "API Key 只会在本次提交时发送到服务端加密保存。",
    deleteConfirm: "确定删除智能体“{name}”吗？此操作无法撤销。",
    agentDeleted: "已删除智能体：{name}",
    agentDeleteFailed: "删除智能体失败。",
    capabilityBinding: "能力绑定",
    capabilityBindingDesc: "能力开关决定 Agent可使用的检索与平台能力；受控 Tool还会经过计划授权和服务端校验。",
    selectedCapabilities: "已选择 {count} 个能力",
    noneSelected: "暂未选择",
    chooseCapabilities: "选择能力",
    cancel: "取消",
    saveChanges: "保存修改",
    addToChat: "添加到对话空间",
    capabilityLibrary: "系统能力库",
    capabilityLibraryDesc: "RAG、工具调用、记忆、语义缓存建议放在平台能力层，再按 Agent 绑定。",
    localRagKnowledge: "本地 RAG 知识",
    localRagDesc: "上传 UTF-8文档到当前账号的服务端知识库；运行时只检索这些带来源和章节的文档。",
    knowledgeTitlePlaceholder: "知识标题，例如：项目定位",
    knowledgeContentPlaceholder: "粘贴一段项目说明、接口约定、业务规则或参考资料。",
    addKnowledge: "上传知识文档",
    emptyKnowledge: "还没有服务端知识文档。上传后可启用 RAG检索。",
    deleteKnowledge: "删除知识文档",
    chooseCapabilityTitle: "选择能力",
    chooseCapabilityDesc: "选择这个 Agent 可以使用的平台能力。",
    done: "完成",
    sequenceTitle: "调用序列图",
    sequenceDesc: "当前 v0.1 采用顺序多 Agent 调用，先保证稳定可用。",
    sequenceSteps: ["用户输入", "筛选启用 Agent", "组装上下文", "调用模型", "接收 SSE 事件", "展示消息"],
    manualAgents: "手动智能体",
    visibleMessages: "可见消息",
    currentSpend: "当前消耗",
    countAgents: "{count} 个",
    countMessages: "{count} 条",
    settingsTitle: "基础设置",
    settingsDesc: "当前版本优先跑通本地 Web MVP。正式生产能力将在下一阶段接入。",
    apiKeyStorage: "API Key 仅在提交时短暂经过浏览器，并由服务端加密保存；页面不会保存或回显明文密钥。",
    futureWork: "数据库、账号系统、密钥加密持久化和桌面端打包属于下一阶段。",
    simulationMode: "未填写 API Key 时，远程模型会进入模拟回复；Ollama 可留空但调用本地服务。",
  },
  en: {
    nav: {
      chat: "Chat",
      creator: "Agents",
      tools: "Capabilities",
      dashboard: "Run Flow",
      settings: "Settings",
    },
    productSubtitle: "Multi-Agent Workspace",
    siderHint: "Create agents first, then send messages in the chat workspace. This version prioritizes local reliability.",
    topDescription: "Create agents, enter a message, and enabled agents will reply in sequence in the same chat.",
    language: "Language",
    zh: "中文",
    en: "English",
    loadedAgents: "Added agents",
    enabledCount: "enabled",
    currentChat: "Current chat",
    chatTargetHint: "Messages are sent to all enabled agents.",
    taskSpaces: "Task spaces",
    spaceCount: "spaces",
    createWorkspace: "Create task space",
    editWorkspace: "Edit task space",
    createFirstWorkspace: "Create your first task space",
    defaultWorkspaceName: "Development report generation",
    defaultWorkspaceDescription: "The requirements analyst and development-report lead collaborate on a detailed development report.",
    workspaceNoDescription: "No task description",
    workspaceAgentCount: "agents",
    workspaceAgents: "Space agents",
    workspaceMember: "Member of this space",
    workspaceName: "Task name",
    workspaceDescription: "Task description (optional)",
    workspaceEditorDesc: "Name this task and select the agents that participate in this conversation and report.",
    selectWorkspaceAgents: "Select space agents",
    configureWorkspace: "Configure task space",
    selectWorkspaceFirst: "Create or select a task space first",
    clearChat: "Clear chat",
    inputPlaceholder: "Type a message for the enabled agents",
    send: "Send",
    noAgents: "No agents yet.",
    addAgent: "Add agent",
    noMessages: "No messages yet.",
    deleteAgent: "Delete agent",
    editAgent: "Edit agent",
    agentEnabled: "Enabled",
    agentDisabled: "Disabled",
    joinReply: "Join replies",
    you: "You",
    thinking: "is generating...",
    needName: "Please enter an agent name.",
    needPrompt: "Please enter a role prompt.",
    needAgent: "Please add and enable at least one agent. Your message has been kept in the chat.",
    sanitizedKey: "Some agent API keys contained Chinese or full-width characters, so those keys were ignored for this run.",
    savedWithSanitizedKey: "Saved {name}, but the API key contained non-ByteString characters and was ignored locally.",
    agentAdded: "Agent added: {name}",
    agentUpdated: "Agent updated: {name}",
    editingAgent: "Editing agent: {name}",
    editCancelled: "Edit cancelled. You can create a new agent now.",
    callFailed: "Model call failed.",
    noStream: "No streaming response received.",
    sendFailed: "Send failed.",
    clearDone: "Chat history cleared. Local agent configuration is still kept.",
    currentAgents: "Current agents",
    currentAgentsDesc: "View, edit, enable, or delete the agents you created.",
    apiUrlLabel: "API URL",
    apiKeyConfigured: "Key configured",
    apiKeyMissing: "No key",
    capabilityNames: "Capabilities: {names}",
    emptyAgentsInCreator: "No agents yet. Create one on the right.",
    capabilityCount: "capabilities",
    createAgent: "Create agent",
    editAgentTitle: "Edit agent: {name}",
    createAgentDesc: "After model connection details are saved, the agent joins the chat workspace.",
    editingHint: "You are editing an existing agent. Saving will overwrite its configuration.",
    cancelEdit: "Cancel edit",
    agentName: "Agent name",
    agentNamePlaceholder: "Example: Product analyst",
    rolePrompt: "Role prompt",
    promptPlaceholder: "Describe the agent's responsibility, voice, and output requirements. Minimum 10 characters.",
    modelSource: "Model source",
    modelName: "Model name",
    apiUrlPlaceholder: "https://api.example.com/v1 or http://localhost:11434",
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "Enter API Key",
    ollamaKeyPlaceholder: "Local Ollama can be left blank",
    apiKeyKeepHint: "Dots mean the key is encrypted and saved. Leave it blank to keep the current key; mask: {key}",
    apiKeyNewHint: "The API Key is sent only for this submission and encrypted on the server.",
    deleteConfirm: "Delete agent “{name}”? This cannot be undone.",
    agentDeleted: "Agent deleted: {name}",
    agentDeleteFailed: "Failed to delete agent.",
    capabilityBinding: "Capability binding",
    capabilityBindingDesc: "Capability switches control retrieval and platform abilities; controlled tools also require plan authorization and server validation.",
    selectedCapabilities: "{count} capabilities selected",
    noneSelected: "None selected",
    chooseCapabilities: "Choose capabilities",
    cancel: "Cancel",
    saveChanges: "Save changes",
    addToChat: "Add to chat",
    capabilityLibrary: "System capability library",
    capabilityLibraryDesc: "RAG, tool calling, memory, and semantic cache should live in the platform capability layer, then be bound per agent.",
    localRagKnowledge: "Local RAG knowledge",
    localRagDesc: "Upload UTF-8 files to this account's server-side library. Runs retrieve only these source- and section-aware documents.",
    knowledgeTitlePlaceholder: "Knowledge title, for example: project positioning",
    knowledgeContentPlaceholder: "Paste project notes, API contracts, business rules, or reference material.",
    addKnowledge: "Upload knowledge file",
    emptyKnowledge: "No server-side knowledge documents yet. Upload one to enable RAG retrieval.",
    deleteKnowledge: "Delete knowledge document",
    chooseCapabilityTitle: "Choose capabilities",
    chooseCapabilityDesc: "Select platform capabilities this agent can use.",
    done: "Done",
    sequenceTitle: "Run sequence",
    sequenceDesc: "v0.1 uses sequential multi-agent calls so the core loop stays reliable.",
    sequenceSteps: ["User input", "Filter enabled agents", "Build context", "Call model", "Receive SSE events", "Show messages"],
    manualAgents: "Manual agents",
    visibleMessages: "Visible messages",
    currentSpend: "Current spend",
    countAgents: "{count}",
    countMessages: "{count}",
    settingsTitle: "Basic settings",
    settingsDesc: "This version prioritizes the local Web MVP. Production capabilities will be added in the next phase.",
    apiKeyStorage: "API keys only pass through the browser during submission and are stored encrypted by the server; plaintext keys are never retained or displayed.",
    futureWork: "Database, account system, encrypted key persistence, and desktop packaging belong to the next phase.",
    simulationMode: "Remote models enter simulation mode when API Key is empty; Ollama can be empty and call the local service.",
  },
} as const;

export type Copy = (typeof copy)[Language];
