export type Language = "zh" | "en";

export const copy = {
  zh: {
    nav: {
      chat: "需求与报告",
      creator: "创建智能体",
      tools: "能力库",
      dashboard: "运行状态",
    settings: "运行与交付设置",
    },
    productSubtitle: "AgentForge｜需求到产品/UI实施报告平台",
    siderHint: "从需求输入开始，经过澄清、规划、评审和人工确认，生成可交给下游 AI 编程 Agent 的产品/UI实施报告。",
    topDescription: "输入产品需求，生成三套可比较的产品/UI实施报告；网站由下游 AI 编程 Agent 实现，完成后回到报告中心验收。",
    language: "语言",
    zh: "中文",
    en: "English",
    loadedAgents: "已添加的智能体",
    enabledCount: "个启用",
    currentChat: "当前需求任务",
    chatTargetHint: "Agent 会先澄清需求，再规划、评审并生成三套产品/UI实施报告。",
    taskSpaces: "需求任务",
    spaceCount: "个空间",
    createWorkspace: "创建需求任务",
    editWorkspace: "编辑需求任务",
    createFirstWorkspace: "创建第一个需求任务",
    defaultWorkspaceName: "产品/UI实施报告",
    defaultWorkspaceDescription: "需求澄清、方案评审与产品/UI报告架构师协作生成可交给下游 AI 编程 Agent 的实施规格。",
    workspaceNoDescription: "暂未填写任务说明",
    workspaceAgentCount: "个智能体",
    workspaceAgents: "空间内智能体",
    workspaceMember: "当前空间成员",
    workspaceName: "任务名称",
    workspaceDescription: "任务说明（可选）",
    workspaceEditorDesc: "为需求任务命名，并选择参与澄清、规划、评审和报告生成的智能体。",
    selectWorkspaceAgents: "选择空间内智能体",
    configureWorkspace: "配置需求任务",
    selectWorkspaceFirst: "请先创建或选择一个需求任务",
    clearChat: "清空当前需求",
    inputPlaceholder: "输入产品需求，例如：为运营团队设计一个可验收的后台管理系统",
    send: "生成报告",
    noAgents: "还没有智能体。",
    addAgent: "添加智能体",
    noMessages: "还没有提交需求。输入一个产品需求后，Agent 会先澄清问题，最终生成三套产品/UI实施报告。",
    deleteAgent: "删除智能体",
    editAgent: "编辑智能体",
    agentEnabled: "已启用",
    agentDisabled: "已停用",
    joinReply: "参与回复",
    you: "你",
    thinking: "正在生成...",
    needName: "请先填写智能体名称。",
    needPrompt: "请填写角色设定 Prompt。",
    needAgent: "请先添加并启用至少一个智能体。当前需求已保留。",
    sanitizedKey: "部分 Agent 的 API Key 包含中文或全角字符，本次已忽略这些 Key 并继续发送。",
    savedWithSanitizedKey: "已保存 {name}，但 API Key 包含中文或全角字符，本地已忽略该 Key。",
    agentAdded: "已添加智能体：{name}",
    agentUpdated: "已更新智能体：{name}",
    editingAgent: "正在编辑智能体：{name}",
    editCancelled: "已取消编辑，可以继续创建新的智能体。",
    callFailed: "模型调用失败。",
    noStream: "没有收到流式响应。",
    sendFailed: "报告生成失败。",
    clearDone: "当前需求记录已清空。本地 Agent 配置仍然保留。",
    currentAgents: "当前智能体",
    currentAgentsDesc: "这里可以查看、编辑、启用或删除已经创建的智能体。",
    apiUrlLabel: "API URL",
    apiKeyConfigured: "已配置密钥",
    apiKeyMissing: "未配置密钥",
    capabilityNames: "能力：{names}",
    emptyAgentsInCreator: "还没有智能体。先在右侧创建一个。",
    capabilityCount: "个能力",
    createAgent: "创建智能体",
    editAgentTitle: "编辑智能体：{name}",
    createAgentDesc: "填写模型连接信息后，智能体可加入需求任务，参与澄清、规划、评审或报告生成。",
    editingHint: "当前正在修改已有智能体，保存后会覆盖原配置。",
    cancelEdit: "取消编辑",
    agentName: "智能体名称",
    agentNamePlaceholder: "例如：需求澄清师",
    rolePrompt: "角色设定 Prompt",
    promptPlaceholder: "描述这个智能体的职责、语气和输出要求。",
    modelSource: "模型来源",
    modelName: "模型名称",
    apiUrlPlaceholder: "https://api.example.com/v1 或 http://localhost:11434",
    apiKeyLabel: "API Key / API 密钥",
    apiKeyPlaceholder: "请输入 API Key",
    ollamaKeyPlaceholder: "Ollama 本地模型可留空",
    apiKeyKeepHint: "圆点表示密钥已加密保存；不输入新值会保留现有密钥。当前掩码：{key}",
    apiKeyNewHint: "API Key 只会在本次提交时发送到服务端加密保存。",
    deleteConfirm: "确定删除智能体“{name}”吗？此操作无法撤销。",
    agentDeleted: "已删除智能体：{name}",
    agentDeleteFailed: "删除智能体失败。",
    capabilityBinding: "能力绑定",
    capabilityBindingDesc: "能力开关决定 Agent可使用的检索与平台能力；受控 Tool还会经过计划授权和服务端校验。",
    selectedCapabilities: "已选择 {count} 个能力",
    noneSelected: "暂未选择",
    chooseCapabilities: "选择能力",
    cancel: "取消",
    saveChanges: "保存修改",
    addToChat: "添加到需求任务",
    capabilityLibrary: "系统能力库",
    capabilityLibraryDesc: "RAG、工具调用、记忆、语义缓存建议放在平台能力层，再按 Agent 绑定。",
    localRagKnowledge: "本地 RAG 知识",
    localRagDesc: "上传 UTF-8文档到当前账号的服务端知识库；运行时只检索这些带来源和章节的文档。",
    knowledgeTitlePlaceholder: "知识标题，例如：项目定位",
    knowledgeContentPlaceholder: "粘贴一段项目说明、接口约定、业务规则或参考资料。",
    addKnowledge: "上传知识文档",
    emptyKnowledge: "还没有服务端知识文档。上传后可启用 RAG检索。",
    deleteKnowledge: "删除知识文档",
    chooseCapabilityTitle: "选择能力",
    chooseCapabilityDesc: "选择这个 Agent 可以使用的平台能力。",
    done: "完成",
    sequenceTitle: "报告生成流程",
    sequenceDesc: "基础工作台展示需求输入、Agent 协作和运行结果，最终交付物请到报告中心查看。",
    sequenceSteps: ["提交需求", "筛选启用 Agent", "组装证据上下文", "运行协作流程", "接收进度事件", "查看报告结果"],
    manualAgents: "参与 Agent",
    visibleMessages: "运行事件",
    currentSpend: "当前消耗",
    countAgents: "{count} 个",
    countMessages: "{count} 条事件",
    settingsTitle: "运行与交付设置",
    settingsDesc: "当前工作台负责生成和验收产品/UI实施规格；真实网站由下游 AI 编程 Agent 生成。",
    apiKeyStorage: "API Key 仅在提交时短暂经过浏览器，并由服务端加密保存；页面不会保存或回显明文密钥。",
    futureWork: "生产化部署、真实 Provider 质量、PostgreSQL 运维和企业级 CI 仍需在目标环境继续验证。",
    simulationMode: "未填写 API Key 时，远程模型会进入模拟回复；Ollama 可留空但调用本地服务。",
  },
  en: {
    nav: {
      chat: "Requirements & Reports",
      creator: "Agents",
      tools: "Knowledge & Tools",
      dashboard: "Run Status",
    settings: "Runtime & Delivery",
    },
    productSubtitle: "AgentForge | Product/UI implementation reports",
    siderHint: "Start with a requirement, then let the workflow clarify, plan, review, and produce a handoff-ready product/UI implementation report.",
    topDescription: "Enter a product requirement to generate three comparable product/UI implementation reports. A downstream AI coding agent builds the site, then you record acceptance results here.",
    language: "Language",
    zh: "中文",
    en: "English",
    loadedAgents: "Added agents",
    enabledCount: "enabled",
    currentChat: "Current requirement task",
    chatTargetHint: "Agents clarify the requirement, plan the work, review alternatives, and produce three product/UI reports.",
    taskSpaces: "Requirement tasks",
    spaceCount: "spaces",
    createWorkspace: "Create requirement task",
    editWorkspace: "Edit requirement task",
    createFirstWorkspace: "Create your first requirement task",
    defaultWorkspaceName: "Product/UI report generation",
    defaultWorkspaceDescription: "Agents clarify the requirement, compare product/UI directions, and produce implementation specifications for a downstream AI coding agent.",
    workspaceNoDescription: "No task description",
    workspaceAgentCount: "agents",
    workspaceAgents: "Space agents",
    workspaceMember: "Member of this space",
    workspaceName: "Task name",
    workspaceDescription: "Task description (optional)",
    workspaceEditorDesc: "Name this requirement task and select the agents for clarification, planning, review, and report generation.",
    selectWorkspaceAgents: "Select space agents",
    configureWorkspace: "Configure requirement task",
    selectWorkspaceFirst: "Create or select a requirement task first",
    clearChat: "Clear requirement",
    inputPlaceholder: "Enter a product requirement, for example: design an auditable admin console for an operations team",
    send: "Generate reports",
    noAgents: "No agents yet.",
    addAgent: "Add agent",
    noMessages: "No requirement submitted yet. Enter one and agents will clarify it before producing three product/UI implementation reports.",
    deleteAgent: "Delete agent",
    editAgent: "Edit agent",
    agentEnabled: "Enabled",
    agentDisabled: "Disabled",
    joinReply: "Join replies",
    you: "You",
    thinking: "is generating...",
    needName: "Please enter an agent name.",
    needPrompt: "Please enter a role prompt.",
    needAgent: "Please add and enable at least one agent. The current requirement has been kept.",
    sanitizedKey: "Some agent API keys contained Chinese or full-width characters, so those keys were ignored for this run.",
    savedWithSanitizedKey: "Saved {name}, but the API key contained non-ByteString characters and was ignored locally.",
    agentAdded: "Agent added: {name}",
    agentUpdated: "Agent updated: {name}",
    editingAgent: "Editing agent: {name}",
    editCancelled: "Edit cancelled. You can create a new agent now.",
    callFailed: "Model call failed.",
    noStream: "No streaming response received.",
    sendFailed: "Report generation failed.",
    clearDone: "The current requirement was cleared. Local agent configuration is still kept.",
    currentAgents: "Current agents",
    currentAgentsDesc: "View, edit, enable, or delete the agents you created.",
    apiUrlLabel: "API URL",
    apiKeyConfigured: "Key configured",
    apiKeyMissing: "No key",
    capabilityNames: "Capabilities: {names}",
    emptyAgentsInCreator: "No agents yet. Create one on the right.",
    capabilityCount: "capabilities",
    createAgent: "Create agent",
    editAgentTitle: "Edit agent: {name}",
    createAgentDesc: "After model connection details are saved, the agent can join requirement tasks for clarification, planning, review, and report generation.",
    editingHint: "You are editing an existing agent. Saving will overwrite its configuration.",
    cancelEdit: "Cancel edit",
    agentName: "Agent name",
    agentNamePlaceholder: "Example: Product analyst",
    rolePrompt: "Role prompt",
    promptPlaceholder: "Describe the agent's responsibility, voice, and output requirements. Minimum 10 characters.",
    modelSource: "Model source",
    modelName: "Model name",
    apiUrlPlaceholder: "https://api.example.com/v1 or http://localhost:11434",
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "Enter API Key",
    ollamaKeyPlaceholder: "Local Ollama can be left blank",
    apiKeyKeepHint: "Dots mean the key is encrypted and saved. Leave it blank to keep the current key; mask: {key}",
    apiKeyNewHint: "The API Key is sent only for this submission and encrypted on the server.",
    deleteConfirm: "Delete agent “{name}”? This cannot be undone.",
    agentDeleted: "Agent deleted: {name}",
    agentDeleteFailed: "Failed to delete agent.",
    capabilityBinding: "Capability binding",
    capabilityBindingDesc: "Capability switches control retrieval and platform abilities; controlled tools also require plan authorization and server validation.",
    selectedCapabilities: "{count} capabilities selected",
    noneSelected: "None selected",
    chooseCapabilities: "Choose capabilities",
    cancel: "Cancel",
    saveChanges: "Save changes",
    addToChat: "Add to chat",
    capabilityLibrary: "System capability library",
    capabilityLibraryDesc: "RAG, tool calling, memory, and semantic cache should live in the platform capability layer, then be bound per agent.",
    localRagKnowledge: "Local RAG knowledge",
    localRagDesc: "Upload UTF-8 files to this account's server-side library. Runs retrieve only these source- and section-aware documents.",
    knowledgeTitlePlaceholder: "Knowledge title, for example: project positioning",
    knowledgeContentPlaceholder: "Paste project notes, API contracts, business rules, or reference material.",
    addKnowledge: "Upload knowledge file",
    emptyKnowledge: "No server-side knowledge documents yet. Upload one to enable RAG retrieval.",
    deleteKnowledge: "Delete knowledge document",
    chooseCapabilityTitle: "Choose capabilities",
    chooseCapabilityDesc: "Select platform capabilities this agent can use.",
    done: "Done",
    sequenceTitle: "Report generation flow",
    sequenceDesc: "This configuration workspace shows requirement input, agent collaboration, and run results; the deliverable reports live in Report Center.",
    sequenceSteps: ["Submit requirement", "Filter enabled agents", "Build evidence context", "Run collaboration", "Receive progress events", "Review reports"],
    manualAgents: "Participating agents",
    visibleMessages: "Run events",
    currentSpend: "Current spend",
    countAgents: "{count}",
    countMessages: "{count} events",
    settingsTitle: "Runtime & delivery settings",
    settingsDesc: "This workspace generates and accepts product/UI implementation specifications; a downstream AI coding agent generates the actual site.",
    apiKeyStorage: "API keys only pass through the browser during submission and are stored encrypted by the server; plaintext keys are never retained or displayed.",
    futureWork: "Production deployment, real-provider quality, PostgreSQL operations, and enterprise CI still require validation in the target environment.",
    simulationMode: "Remote models enter simulation mode when API Key is empty; Ollama can be empty and call the local service.",
  },
} as const;

export type Copy = (typeof copy)[Language];
