import sys, os
path = r"G:\projects\agent-learning\projects\Multi-Agent-Workspace\scripts\verify-e2e.py"
lines = [
    "# -*- coding: utf-8 -*-",
    "import json, urllib.request, urllib.error, io, sys, datetime",
    "",
    'BASE = "http://localhost:3000"',
    "",
    "def req(method, path, body=None):",
    '    url = BASE + path',
    '    data = json.dumps(body).encode("utf-8") if body else None',
    '    r = urllib.request.Request(url, data=data, method=method, headers={"Content-Type": "application/json"})',
    "    try:",
    "        with urllib.request.urlopen(r, timeout=60) as resp:",
    "            raw = resp.read()",
    "            try:",
    '                return resp.status, raw.decode("utf-8"), True',
    "            except:",
    '                return resp.status, raw.decode("latin-1"), True',
    "    except urllib.error.HTTPError as e:",
    '        return e.code, e.read().decode("utf-8", errors="replace"), False',
    "",
    'log = io.open(r"G:\\projects\\agent-learning\\projects\\Multi-Agent-Workspace\\scripts\\verify-e2e.log", "w", encoding="utf-8")',
    "",
    "def p(msg):",
    "    print(msg)",
    '    log.write(msg + "\\n")',
    "",
    'p("=" * 60)',
    'p("START " + datetime.datetime.now().isoformat())',
    "",
    'p("\\n--- Step 1: POST /api/agents ---")',
    "agent = {",
    '    "name": "Verify Agent",',
    '    "avatar": "VA",',
    '    "color": "#10b981",',
    '    "provider": "ollama",',
    '    "model": "llama3.1",',
    '    "systemPrompt": "Reply concisely.",',
    '    "temperature": 0.7,',
    '    "maxTokens": 200,',
    '    "capabilityIds": [],',
    '    "apiUrl": "http://localhost:11434",',
    '    "apiKey": "",',
    "}",
    'status, raw, ok = req("POST", "/api/agents", agent)',
    'p("  status=%d ok=%s" % (status, ok))',
    'agent_id = json.loads(raw)["id"]',
    'p("  agent_id=%s" % agent_id)',
    'p("  apiKey=%r apiUrl=%r" % (json.loads(raw).get("apiKey"), json.loads(raw).get("apiUrl")))',
    "",
    'p("\\n--- Step 2: SSE ---")',
    "run_body = {",
    '    "input": "Hello, 10 words.",',
    "    "agents": [{",
    '        "id": agent_id, "name": "Verify Agent", "avatar": "VA",',
    '        "color": "#10b981", "provider": "ollama",',
    '        "model": "llama3.1", "systemPrompt": "Reply concisely.",',
    '        "temperature": 0.7, "maxTokens": 200,',
    '        "capabilityIds": [], "apiUrl": "http://localhost:11434",',
    '        "apiKey": "", "enabled": True,',
    "    }],",
    '    "useRag": False, "knowledgeSnippets": [],',
    "}",
    "events = []",
    'status, raw, ok = req("POST", "/api/workspaces/manual/run", run_body)',
    'p("  status=%d len=%d" % (status, len(raw)))',
    'for line in raw.split("\\n"):',
    '    if line.startswith("data: "):',
    "        try:",
    "            events.append(json.loads(line[6:]))",
    "        except Exception:",
    "            pass",
    'p("  events=%d" % len(events))',
    "for ev in events:",
    '    t = ev.get("type","?")',
    '    if t == "agent_completed":',
    '        p("  - %s: %s" % (t, ev.get("message",{}).get("content","")[:100]))',
    '    elif t == "agent_failed":',
    '        p("  - %s: %s" % (t, ev.get("error","")[:100]))',
    "    else:",
    '        p("  - %s" % t)',
    "",
    'p("\\n--- Step 3: persistence ---")',
    'status, raw, ok = req("GET", "/api/agents")',
    "agents = json.loads(raw)",
    'ok_persist = any(a["id"] == agent_id for a in agents)',
    'p("  count=%d persisted=%s" % (len(agents), ok_persist))',
    "",
    'status, raw, ok = req("GET", "/api/workspaces/manual/messages")',
    'msgs = json.loads(raw)',
    'p("  messages=%d" % len(msgs))',
    "",
    'status, raw, ok = req("GET", "/api/dashboard/stats")',
    'p("  stats=%s" % raw[:200])',
    "",
    'p("\\nDONE")',
    "log.close()",
]
with io.open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\\n")
print("[OK] wrote %d lines to %s" % (len(lines), path))
